spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/impulz
  elasticsearch:
    uris: http://elasticsearch:9200
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: https://auth.impulz.online/realms/Impulz/protocol/openid-connect/certs
  data:
    redis:
      host: redis

keycloak:
  keycloakUrl: https://auth.impulz.online

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.security: INFO
